import { USelection } from "src/selection";
import { render, screen, waitFor } from "@testing-library/react";
import { HydraulicModelBuilder } from "src/__helpers__/hydraulic-model-builder";
import { defaultSimulationSettings } from "src/simulation/simulation-settings";
import { selectionAtom } from "src/state/selection";
import { inpFileInfoAtom } from "src/state/file-system";
import {
  stagingModelDerivedAtom,
  simulationDerivedAtom,
} from "src/state/derived-branch-state";
import { momentLogAtom } from "src/state/model-changes";
import { SimulationFinished } from "src/state/simulation";
import { Store } from "src/state";
import { MomentLog } from "src/lib/persistence/moment-log";
import userEvent from "@testing-library/user-event";
import { aTestFile } from "src/__helpers__/file";
import { aFileInfo, setInitialState } from "src/__helpers__/state";
import { CommandContainer } from "./__helpers__/command-container";
import {
  buildFileSystemHandleMock,
  lastSaveCall,
  stubFileOpen,
  stubFileSave,
} from "src/__helpers__/browser-fs-mock";
import { buildInp } from "src/simulation/build-inp";
import { checksum } from "src/infra/checksum";
import { presets } from "@epanet-js/project-settings";
import { waitForNotLoading } from "src/__helpers__/ui-expects";
import { getByLabel } from "src/__helpers__/asset-queries";
import { useOpenInpFromFs } from "./open-inp-from-fs";
import { stubUserTracking } from "src/__helpers__/user-tracking";
import { userSettingsAtom } from "src/state/user-settings";
import { useInProcessDb } from "src/lib/db/__test-helpers__/in-process-db";
import * as db from "src/lib/db";
import { recentFilesStoreAtom } from "src/state/file-system";

describe("openInpFromFs", () => {
  useInProcessDb();
  it("registers in state when the inp was generated by the app", async () => {
    const IDS = { J1: 1 } as const;
    const newHandle = stubFileOpen();
    const store = setInitialState();

    renderComponent({ store });

    const inp = anInpMadeByTheApp({ junctionId: IDS.J1 });
    const file = aTestFile({ filename: "my-network.inp", content: inp });
    await triggerCommand();

    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    const hydraulicModel = store.get(stagingModelDerivedAtom);
    expect(getByLabel(hydraulicModel.assets, "1")).toBeTruthy();

    expect(store.get(inpFileInfoAtom)!.handle).toEqual(newHandle);
    expect(store.get(inpFileInfoAtom)!.isMadeByApp).toEqual(true);
  });

  it("captures a user tracking events", async () => {
    const userTracking = stubUserTracking();
    stubFileOpen();
    const store = setInitialState();

    renderComponent({ store });

    const inp = minimalInp();
    const file = aTestFile({ filename: "my-network.inp", content: inp });
    await triggerCommand();

    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    expect(userTracking.capture).toHaveBeenCalledWith({
      name: "openInp.started",
      source: "shortcut",
    });
    expect(userTracking.capture).toHaveBeenCalledWith(
      expect.objectContaining({
        name: "importInp.completed",
      }),
    );
  });

  it("registers in state when the inp was NOT generated by the app", async () => {
    stubFileOpen();
    const store = setInitialState();

    renderComponent({ store });

    const inp = minimalInp({ junctionId: "J1" });
    const file = aTestFile({ filename: "my-network.inp", content: inp });
    await triggerCommand();

    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    const hydraulicModel = store.get(stagingModelDerivedAtom);
    expect(getByLabel(hydraulicModel.assets, "J1")).toBeTruthy();

    expect(store.get(inpFileInfoAtom)!.handle).toEqual(undefined);
    expect(store.get(inpFileInfoAtom)!.isMadeByApp).toEqual(false);
  });

  it("displays error when cannot process", async () => {
    const userTracking = stubUserTracking();
    stubFileOpen();
    const store = setInitialState({
      hydraulicModel: HydraulicModelBuilder.empty(),
    });
    const file = aTestFile({ content: "INVALID" });

    renderComponent({ store });

    await triggerCommand();

    await doFileSelection(file);

    await waitFor(() =>
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument(),
    );

    expect(screen.getByText(/failed to open model/i)).toBeInTheDocument();
    await userEvent.click(screen.getByText(/understood/i));

    expect(screen.queryByText(/error/i)).not.toBeInTheDocument();
    expect(userTracking.capture).toHaveBeenCalledWith({
      name: "invalidFilesError.seen",
    });
  });

  it("removes previous state", async () => {
    const IDS = { J1: 1, ANY: 2, P1: 3 } as const;
    stubFileOpen();
    const inp = minimalInp({ junctionId: "J1" });
    const previousSimulation: SimulationFinished = {
      status: "failure",
      report: "ERROR",
      modelVersion: "10",
      settingsVersion: "",
    };
    const previousSelection = USelection.fromAssetIds([IDS.ANY]);
    const previousMomentLog = new MomentLog();
    const store = setInitialState({
      hydraulicModel: HydraulicModelBuilder.empty(),
      momentLog: previousMomentLog,
      simulation: previousSimulation,
      selection: previousSelection,
      fileInfo: aFileInfo({
        handle: buildFileSystemHandleMock({ fileName: "old.inp" }),
      }),
      isProjectSaved: false,
    });
    const file = aTestFile({ filename: "my-network.inp", content: inp });

    renderComponent({ store });
    await triggerCommand();

    await waitFor(() =>
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument(),
    );
    await waitForNotLoading();
    await userEvent.click(screen.getByRole("button", { name: /discard/i }));
    await waitForNotLoading();
    await doFileSelection(file);

    await waitFor(() =>
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument(),
    );

    const hydraulicModel = store.get(stagingModelDerivedAtom);
    const selection = store.get(selectionAtom);
    expect(getByLabel(hydraulicModel.assets, "J1")).toBeTruthy();
    expect(getByLabel(hydraulicModel.assets, "P1")).toBeFalsy();

    const updatedMomentLog = store.get(momentLogAtom);
    expect(updatedMomentLog.id).not.toEqual(previousMomentLog.id);

    const simulation = store.get(simulationDerivedAtom);
    expect(simulation.status).toEqual("idle");

    expect(USelection.isNone(selection)).toBe(true);
  });

  it("can save previous changes before opening", async () => {
    const IDS = { J1: 1 } as const;
    stubFileOpen();
    stubFileSave({ fileName: "my-project.ejsdb" });
    const inp = minimalInp({ junctionId: "J1" });
    const hydraulicModel = HydraulicModelBuilder.with()
      .aJunction(IDS.J1)
      .build();
    const store = setInitialState({
      hydraulicModel,
      isProjectSaved: false,
    });
    store.set(userSettingsAtom, {
      showFirstScenarioDialog: true,
      showProjectSavedInfo: false,
      showFileFormatUpdated: false,
    });
    await db.importProject({
      newDb: true,
      hydraulicModel,
      simulationSettings: defaultSimulationSettings,
    });
    const file = aTestFile({ filename: "my-network.inp", content: inp });

    renderComponent({ store });

    await triggerCommand();

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });
    expect(screen.getByText(/unsaved/i)).toBeInTheDocument();

    await userEvent.click(
      screen.getByRole("button", { name: /save and continue/i }),
    );

    await waitForNotLoading();

    const lastSave = lastSaveCall();

    expect(lastSave.contentBlob).toBeDefined();

    await waitFor(() =>
      expect(screen.queryByText(/unsaved/i)).not.toBeInTheDocument(),
    );
    await waitForNotLoading();
    await doFileSelection(file);

    await waitForNotLoading();

    const openedModel = store.get(stagingModelDerivedAtom);
    expect(getByLabel(openedModel.assets, "J1")).toBeTruthy();

    expect(store.get(inpFileInfoAtom)!.handle).toEqual(undefined);
  });

  it("can discard changes when opening a new project", async () => {
    const inp = minimalInp({ junctionId: "J1" });
    const store = setInitialState({
      hydraulicModel: HydraulicModelBuilder.empty(),
      isProjectSaved: false,
    });
    const file = aTestFile({ filename: "my-network.inp", content: inp });

    renderComponent({ store });

    await triggerCommand();

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });
    expect(screen.getByText(/unsaved/i)).toBeInTheDocument();

    await userEvent.click(screen.getByRole("button", { name: /discard/i }));

    await waitFor(() =>
      expect(screen.queryByText(/unsaved/i)).not.toBeInTheDocument(),
    );
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    const hydraulicModel = store.get(stagingModelDerivedAtom);
    expect(getByLabel(hydraulicModel.assets, "J1")).toBeTruthy();
  });

  it("doesnt create model when coordinates not supported", async () => {
    const inp = inpWithoutCoordinates({ junctionId: "J1" });
    const store = setInitialState({
      hydraulicModel: HydraulicModelBuilder.empty(),
    });
    const file = aTestFile({ filename: "my-network.inp", content: inp });

    renderComponent({ store });

    await triggerCommand();

    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    expect(screen.getByText(/coordinates missing/i)).toBeInTheDocument();

    await userEvent.click(screen.getByRole("button", { name: /understood/i }));

    expect(screen.queryByText(/coordinates missing/i)).not.toBeInTheDocument();
    const hydraulicModel = store.get(stagingModelDerivedAtom);
    expect(hydraulicModel.assets.size).toEqual(0);
  });

  it("shows warning when using unsupported features", async () => {
    const inp = inpWithUnsupportedFeatures({ junctionId: "J1" });
    const store = setInitialState({
      hydraulicModel: HydraulicModelBuilder.empty(),
    });
    const file = aTestFile({ filename: "my-network.inp", content: inp });

    renderComponent({ store });

    await triggerCommand();

    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    expect(
      screen.getByText(/partially supported features/i),
    ).toBeInTheDocument();

    await userEvent.click(screen.getByRole("button", { name: /understood/i }));

    expect(screen.queryByText(/coordinates missing/i)).not.toBeInTheDocument();
    const hydraulicModel = store.get(stagingModelDerivedAtom);
    expect(getByLabel(hydraulicModel.assets, "J1")).toBeTruthy();
  });
});

describe("file format updated dialog", () => {
  useInProcessDb();

  beforeEach(() => {
    localStorage.clear();
  });

  it("shows the dialog after a clean import", async () => {
    stubFileOpen();
    const store = setInitialState();
    const file = aTestFile({
      filename: "my-network.inp",
      content: minimalInp(),
    });

    renderComponent({ store });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    expect(screen.getByText(/file format updated/i)).toBeInTheDocument();
  });

  it("does not show the dialog when the user has skipped it", async () => {
    stubFileOpen();
    const store = setInitialState();
    store.set(userSettingsAtom, {
      showFirstScenarioDialog: true,
      showProjectSavedInfo: true,
      showFileFormatUpdated: false,
    });
    const file = aTestFile({
      filename: "my-network.inp",
      content: minimalInp(),
    });

    renderComponent({ store });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    expect(screen.queryByText(/file format updated/i)).not.toBeInTheDocument();
  });

  it("persists the skip preference when checkbox is ticked on Understood", async () => {
    stubFileOpen();
    const store = setInitialState();
    const file = aTestFile({
      filename: "my-network.inp",
      content: minimalInp(),
    });

    renderComponent({ store });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    await userEvent.click(screen.getByRole("checkbox"));
    await userEvent.click(screen.getByRole("button", { name: /understood/i }));

    await waitFor(() => {
      expect(
        screen.queryByText(/file format updated/i),
      ).not.toBeInTheDocument();
    });
    expect(store.get(userSettingsAtom).showFileFormatUpdated).toBe(false);
  });

  it("keeps the skip preference at default when Understood is clicked without ticking", async () => {
    stubFileOpen();
    const store = setInitialState();
    const file = aTestFile({
      filename: "my-network.inp",
      content: minimalInp(),
    });

    renderComponent({ store });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    await userEvent.click(screen.getByRole("button", { name: /understood/i }));

    await waitFor(() => {
      expect(
        screen.queryByText(/file format updated/i),
      ).not.toBeInTheDocument();
    });
    expect(store.get(userSettingsAtom).showFileFormatUpdated).toBe(true);
  });

  it("chains after the inp issues dialog when the import has issues", async () => {
    stubFileOpen();
    const store = setInitialState({
      hydraulicModel: HydraulicModelBuilder.empty(),
    });
    const file = aTestFile({
      filename: "my-network.inp",
      content: inpWithUnsupportedFeatures({ junctionId: "J1" }),
    });

    renderComponent({ store });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    expect(
      screen.getByText(/partially supported features/i),
    ).toBeInTheDocument();
    expect(screen.queryByText(/file format updated/i)).not.toBeInTheDocument();

    await userEvent.click(screen.getByRole("button", { name: /understood/i }));

    await waitFor(() => {
      expect(screen.getByText(/file format updated/i)).toBeInTheDocument();
    });
  });

  it("adds the opened inp to recent files", async () => {
    const newHandle = stubFileOpen();
    const store = setInitialState();

    renderComponent({ store });

    const inp = minimalInp({ junctionId: "J1" });
    const file = aTestFile({ filename: "my-network.inp", content: inp });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() => {
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument();
    });

    await waitFor(async () => {
      const entries = await store.get(recentFilesStoreAtom).getAll();
      expect(entries).toHaveLength(1);
      expect(entries[0].name).toBe("my-network.inp");
      expect(entries[0].handle).toBe(newHandle);
    });
  });

  it("shows an error notification and rolls back when the db import fails", async () => {
    stubFileOpen();
    const previousModel = HydraulicModelBuilder.empty();
    const store = setInitialState({ hydraulicModel: previousModel });
    const file = aTestFile({
      filename: "my-network.inp",
      content: minimalInp({ junctionId: "J1" }),
    });
    const spy = vi
      .spyOn(db, "importProject")
      .mockRejectedValueOnce(
        new Error("Junction 1 (J1): row does not match schema"),
      );

    renderComponent({ store });
    await triggerCommand();
    await doFileSelection(file);

    await waitFor(() =>
      expect(screen.queryByText(/loading/i)).not.toBeInTheDocument(),
    );

    expect(screen.getByText(/couldn't open project/i)).toBeInTheDocument();
    expect(
      screen.getByText(/if the error persists, contact support/i),
    ).toBeInTheDocument();
    expect(store.get(stagingModelDerivedAtom)).toBe(previousModel);
    expect(screen.queryByText(/file format updated/i)).not.toBeInTheDocument();

    spy.mockRestore();
  });
});

const triggerCommand = async () => {
  await userEvent.click(screen.getByRole("button", { name: "openInpFromFs" }));
};

const doFileSelection = async (file: File) => {
  await userEvent.upload(screen.getByTestId("file-upload"), file);
};

const TestableComponent = () => {
  const openInpFromFs = useOpenInpFromFs();

  return (
    <button
      aria-label="openInpFromFs"
      onClick={() => openInpFromFs({ source: "shortcut" })}
    >
      Open from fs
    </button>
  );
};
const minimalInp = ({
  junctionId = "J1",
}: { junctionId?: string } = {}): string => {
  return `
    [JUNCTIONS]
    ${junctionId}\t10
    [COORDINATES]
    ${junctionId}\t1\t2
    `;
};
const inpWithUnsupportedFeatures = ({
  junctionId = "J1",
}: {
  junctionId?: string;
}): string => {
  return `
    [JUNCTIONS]
    ${junctionId}\t10
    [UNSUPPORTED]
    ANY
    [COORDINATES]
    ${junctionId}\t1\t2
    `;
};

const inpWithoutCoordinates = ({
  junctionId = "J1",
}: {
  junctionId?: string;
} = {}): string => {
  return `
    [JUNCTIONS]
    ${junctionId}\t10
    `;
};

const anInpMadeByTheApp = ({ junctionId }: { junctionId: number }) => {
  const hydraulicModel = HydraulicModelBuilder.with()
    .aJunction(junctionId, { coordinates: [10, 10] })
    .build();
  const content = buildInp(hydraulicModel, {
    simulationSettings: defaultSimulationSettings,
    units: presets.LPS.units,
    geolocation: true,
  });
  return `;MADE BY EPANET-JS [${checksum(content)}]\n${content}`;
};

const renderComponent = ({ store }: { store: Store }) => {
  render(
    <CommandContainer store={store}>
      <TestableComponent />
    </CommandContainer>,
  );
};
